---

container_workloads:
- name: hello-world-frontend
  image: quay.io/skupper/hello-world-frontend # TODO externalize
  expose: "8080:8080"

application_resources:
- apiVersion: skupper.io/v2alpha1
  kind: Listener
  metadata:
    name: backend
    namespace: "{{ inventory_hostname }}"
  spec:
    routingKey: backend
    port: 8082
    host: 0.0.0.0
