---

container_workloads:
- name: hello-world-frontend
  image: quay.io/skupper/hello-world-frontend # TODO externalize
  expose: "8080:8080"

listener_host:
  kubernetes: backend
  docker: 0.0.0.0
  podman: 0.0.0.0
  linux: 0.0.0.0

application_resources:
- apiVersion: skupper.io/v2alpha1
  kind: Listener
  metadata:
    name: backend
    namespace: "{{ inventory_namespace }}"
  spec:
    routingKey: backend
    port: 8082
    host: "{{ listener_host[skupper_platform] }}"

url_host:
  kubernetes: backend
  docker: localhost
  podman: localhost
  linux: localhost

application_url_checks:
- url: http://{{ url_host[skupper_platform] }}:8082/api/hello
