---

- name: Verify on systems
  hosts: docker,podman,systemd
  gather_facts: no
  tasks:
  - debug:
      var: application_url_checks
  - name: Check URI
    ansible.builtin.uri:
      url: "{{ item.url }}"
      return_content: true
    loop: "{{ application_url_checks | default ([]) }}"
    register: uri_check_result
    until: uri_check_result is success
    retries: "{{ 10 * ( ks_retry_multiplier | default (1) | int ) }}"
    delay: 6
  - name: Show response
    ansible.builtin.debug:
      var: uri_check_result
- name: Verify on Kube
  hosts: kube
  gather_facts: no
  tasks:
  - name: Check URI
    kubernetes.core.k8s_exec:
      kubeconfig: "{{ kubeconfig | default (omit) }}"
      namespace: "{{ inventory_namespace }}"
      command: "curl -v {{ item.url }}"
      pod: lanyard
    loop: "{{ application_url_checks | default ([]) }}"
    register: uri_check_result
    until: uri_check_result is success
    retries: "{{ 10 * ( ks_retry_multiplier | default (1) | int ) }}"
    delay: 6
