---

podman:
  hosts:
    system-frontend-1:
docker:
  hosts:
    system-backend-1:
systemd:
  hosts:
    system-hub-1:

backends:
  hosts:
    system-backend-1:
frontends:
  hosts:
    system-frontend-1:
hubs:
  hosts:
    system-hub-1:
