---

site_spec:
  linkAccess: "{{ 'default' if skupper_platform == 'kubernetes' else omit }}"

site_resources:
- apiVersion: skupper.io/v2alpha1
  kind: RouterAccess
  metadata:
    name: access-1
  spec:
    roles:
      - port: 55671
        name: inter-router
      - port: 45671
        name: edge
    bindHost: "{{ ansible_host }}"
