---

- name: Create the site resource
  skupper.v2.resource:
    namespace: "{{ inventory_hostname }}"
    platform: "{{ skupper_platform }}"
    def:
      apiVersion: skupper.io/v2alpha1
      kind: Site
      metadata:
        name: "{{ inventory_hostname }}"
        namespace: "{{ inventory_hostname }}"
      spec: "{{ site_spec | default(omit) }} "

- name: Create the site resources
  skupper.v2.resource:
    namespace: "{{ inventory_hostname }}"
    platform: "{{ skupper_platform }}"
    def: "{{ item }}"
  loop: "{{ site_resources | default ([]) }}"

- name: Setup the site
  skupper.v2.system:
    namespace: "{{ inventory_hostname }}"
    platform: "{{ skupper_platform }}"
  register: system_results

- name: Show results
  ansible.builtin.debug:
    var: system_results
    verbosity: 1
  when: system_results is defined
