---

- name: Create Skupper resources
  hosts: all
  gather_facts: no
  tasks:
  - debug:
      var: application_resources
      verbosity: 1
  - name: Create Skupper resources
    skupper.v2.resource:
      kubeconfig: "{{ kubeconfig | default (omit) }}"
      state: latest
      definition: "{{ item }}"
      platform: "{{ skupper_platform }}"
      namespace: "{{ inventory_namespace }}"
    loop: "{{ application_resources | default ([]) }}"
    notify: Reload site
  handlers:
  - name: Reload site
    skupper.v2.system:
      action: reload
      image: "{{ cli_image }}"
      namespace: "{{ inventory_namespace }}"
      platform: "{{ skupper_platform }}"
    environment:
      SKUPPER_ROUTER_IMAGE: "{{ router_image | default (omit) }}"
    when: skupper_platform_type == "system"
